### ISSUE TITLE
Bug on MAC OS runner

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#177]
In sage-flatsurf with exact-real installed from conda we got (see [this run](https://github.com/flatsurf/sage-flatsurf/actions/runs/9438455220/job/25995450922?pr=286))
```
sage -t --long --random-seed=339939994485347779404823229766692597382 flatsurf/geometry/categories/half_translation_surfaces.py
**********************************************************************
File "flatsurf/geometry/categories/half_translation_surfaces.py", line 373, in flatsurf.geometry.categories.half_translation_surfaces.HalfTranslationSurfaces.Oriented.FiniteType.ParentMethods.normalized_coordinates
Failed example:
    from pyexactreal import ExactReals  # optional: exactreal  # random output due to pkg_resources deprecation warnings
Exception raised:
    Traceback (most recent call last):
      File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/sage/doctest/forker.py", line 709, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/sage/doctest/forker.py", line 1144, in compile_and_execute
        exec(compiled, globs)
      File "<doctest flatsurf.geometry.categories.half_translation_surfaces.HalfTranslationSurfaces.Oriented.FiniteType.ParentMethods.normalized_coordinates[27]>", line 1, in <module>
        from pyexactreal import ExactReals  # optional: exactreal  # random output due to pkg_resources deprecation warnings
      File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/pyexactreal/__init__.py", line 73, in <module>
        from .cppyy_exactreal import exactreal, ZZModule, QQModule, NumberFieldModule
      File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/pyexactreal/cppyy_exactreal.py", line 35, in <module>
        from cppyythonizations.pickling.cereal import enable_cereal
      File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/cereal.py", line 115, in <module>
        cppyy.include(os.path.join(os.path.dirname(__file__), '..', 'include/cereal/details/static_object.hpp'))
      File "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyy/__init__.py", line 295, in include
        raise ImportError('Failed to load header file "%s"%s' % (header, err.err))
    ImportError: Failed to load header file "/Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp"
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:59:
    In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/__assert:14:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/__verbose_abort:24:18: error: unknown type name '_LIBCPP_AVAILABILITY_VERBOSE_ABORT'
    _LIBCPP_NORETURN _LIBCPP_AVAILABILITY_VERBOSE_ABORT _LIBCPP_OVERRIDABLE_FUNC_VIS _LIBCPP_ATTRIBUTE_FORMAT(__printf__, 1, 2)
                     ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:62:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/__exception/exception.h:72:33: error: redefinition of 'exception'
    class _LIBCPP_EXPORTED_FROM_ABI exception {
                                    ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/exception:99:29: note: previous definition is here
    class _LIBCPP_EXCEPTION_ABI exception
                                ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:62:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/__exception/exception.h:81:33: error: redefinition of 'bad_exception'
    class _LIBCPP_EXPORTED_FROM_ABI bad_exception : public exception {
                                    ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/exception:109:29: note: previous definition is here
    class _LIBCPP_EXCEPTION_ABI bad_exception
                                ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    In file included from /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:63:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/__type_traits/is_constant_evaluated.h:26:53: error: redefinition of '__libcpp_is_constant_evaluated'
    _LIBCPP_HIDE_FROM_ABI inline _LIBCPP_CONSTEXPR bool __libcpp_is_constant_evaluated() _NOEXCEPT {
                                                        ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:4277:6: note: previous definition is here
    bool __libcpp_is_constant_evaluated() _NOEXCEPT { return __builtin_is_constant_evaluated(); }
         ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:195:8: error: redefinition of '__type_info_implementations'
    struct __type_info_implementations {
           ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/typeinfo:182:8: note: previous definition is here
    struct __type_info_implementations {
           ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:302:33: error: redefinition of 'type_info'
    class _LIBCPP_EXPORTED_FROM_ABI type_info
                                    ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/typeinfo:299:67: note: previous definition is here
    class _LIBCPP_EXCEPTION_ABI _LIBCPP_TYPE_INFO_VTABLE_POINTER_AUTH type_info
                                                                      ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:357:33: error: redefinition of 'bad_cast'
    class _LIBCPP_EXPORTED_FROM_ABI bad_cast
                                    ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/typeinfo:347:29: note: previous definition is here
    class _LIBCPP_EXCEPTION_ABI bad_cast
                                ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:367:33: error: redefinition of 'bad_typeid'
    class _LIBCPP_EXPORTED_FROM_ABI bad_typeid
                                    ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/typeinfo:357:29: note: previous definition is here
    class _LIBCPP_EXCEPTION_ABI bad_typeid
                                ^
    In file included from input_line_25:1:
    In file included from /Users/runner/miniconda3/envs/test/lib/python3.10/site-packages/cppyythonizations/pickling/../include/cereal/details/static_object.hpp:58:
    /Users/runner/miniconda3/envs/test/bin/../include/c++/v1/typeinfo:406:6: error: redefinition of '__throw_bad_cast'
    void __throw_bad_cast()
         ^
    /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/typeinfo:372:6: note: previous definition is here
    void __throw_bad_cast()
         ^

**********************************************************************
```

**Comment by saraedum** [comment]
See https://github.com/conda-forge/cppyy-feedstock/issues/78

**Comment by saraedum** [comment]
This is a generic problem with cppyy and an incompatibility with the xcode on GitHub runners and the libcxx provided by conda-forge. I am closing this here since it's not exact-real specific.
